### ISSUE TITLE
Some problem about the defence 

### ISSUE THREAD

**Issue by JoyRider0716** [Megum1/LOTUS#3]
hi,Dear author, I am very interested in your article, but I have some confusion and hope to receive your guidance.

In the [LOTUS](https://openaccess.thecvf.com/content/CVPR2024/html/Cheng_LOTUS_Evasive_and_Resilient_Backdoor_Attacks_through_Sub-Partitioning_CVPR_2024_paper.html) and [OrthogLinearBackdoor](https://github.com/KaiyuanZh/OrthogLinearBackdoor/blob/main/backdoor_mitigation.py)

I found that the final results of nc detection using CIFAR-10 and ResNet18 in both articles seem inconsistent。

The results of your article are as follows:
![image](https://github.com/user-attachments/assets/234e8263-3037-48db-943b-40541b5c842d)
In the article OrthogLinearBackdoor, the results are as follows:
![image](https://github.com/user-attachments/assets/06920df7-ae04-4b55-a2e1-29a79c696301)

**Comment by JoyRider0716** [comment]
I noticed that you also seem to be the author of the OrthogLinearBackdoor paper

**Comment by Megum1** [comment]
Hi there,

Thanks for your interest and for reaching out with your questions! We're happy to address them.

Regarding NC, the numbers presented in the figure and table represent anomaly scores. Any model with a score greater than 2 is considered to contain a backdoor. As shown, the results for the attacks in both the figure and table are largely consistent, despite some minor fluctuations. For instance, the NC score for BadNets in the figure is 4.3, while in the table it is 7.7. Both scores indicate that BadNets is easily detected by NC. These variations may arise from differences in random seeds and the specific trigger patterns used in BadNets, but the overall conclusion remains consistent.

If you experiment with implementing BadNets using different trigger sizes, patterns, or random seeds, you will likely observe similar fluctuations in the anomaly scores. However, these scores should consistently exceed 2, indicating that the models are backdoored.

Thanks again for your thoughtful comments!

**Comment by JoyRider0716** [comment]
> Hi there,
> 
> Thanks for your interest and for reaching out with your questions! We're happy to address them.
> 
> Regarding NC, the numbers presented in the figure and table represent anomaly scores. Any model with a score greater than 2 is considered to contain a backdoor. As shown, the results for the attacks in both the figure and table are largely consistent, despite some minor fluctuations. For instance, the NC score for BadNets in the figure is 4.3, while in the table it is 7.7. Both scores indicate that BadNets is easily detected by NC. These variations may arise from differences in random seeds and the specific trigger patterns used in BadNets, but the overall conclusion remains consistent.
> 
> If you experiment with implementing BadNets using different trigger sizes, patterns, or random seeds, you will likely observe similar fluctuations in the anomaly scores. However, these scores should consistently exceed 2, indicating that the models are backdoored.
> 
> Thanks again for your thoughtful comments!

Thank you very much for your reply, which let me know how I can improve it. I will close this issue later.
